/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import type { AccountAuditEntry } from './accountStore';
import { AccountRow } from './accountTypes';

/**
 * Dữ liệu mẫu cho [IMS-018] Quản lý tài khoản.
 *
 * Tài khoản nội bộ gồm hai nhóm:
 *   - Năm persona đăng nhập được của `INITIAL_USERS` (admin, huong_qlny,
 *     dung_tttt, nam_cntt, thao_cntt) — cùng `loginName` để màn này và màn đăng
 *     nhập nói về cùng một người: khóa tài khoản ở đây là persona đó bị chặn đăng
 *     nhập thật.
 *   - Các tài khoản Phòng Trái phiếu ở cả ba cấp, vì luật cấp độ của SRS chỉ có ý
 *     nghĩa ở phòng này (Bảng 05 mục 5). Đăng nhập bằng `lan.nt` (TP cấp 1),
 *     `minh.dv` (TP cấp 2), `ha.pt` (TP cấp 3) để thử từng mức quyền.
 *
 * `huong_qlny` và `nam_cntt` cố ý KHÔNG bật GA/CA/SMS: tài khoản bật một trong
 * ba phương thức phải qua bước OTP khi đăng nhập, hai persona này giữ đường vào
 * nhanh cho người thử các màn khác.
 *
 * Mọi tài khoản mẫu dùng mật khẩu `demo-password` — đúng chuỗi mà nút "Tài khoản
 * thử nghiệm" của màn đăng nhập tự điền. Riêng `hoa.lt` đang chờ đổi mật khẩu lần
 * đầu với mật khẩu tạm `Tam@2026hnx`, để thử IMS-018-7 không cần tạo tài khoản mới.
 *
 * Tài khoản tổ chức lấy đúng tên tổ chức của hồ sơ TCPH (`dossierSeed.ts`) và Tổ
 * chức liên quan (`relatedOrgMock.ts`), để widget "Tổ chức chưa tạo tài khoản"
 * (IMS-018-8) đối chiếu ra đúng những tổ chức còn thiếu.
 */

const DEMO_PASSWORD = 'demo-password';

type Seed = Partial<AccountRow> &
  Pick<AccountRow, 'loginName' | 'accountType' | 'fullName' | 'email' | 'role' | 'createdDate'>;

let seedId = 0;
function acc(s: Seed): AccountRow {
  seedId += 1;
  return {
    id: seedId,
    statusFlg: 1,
    activeFlg: 1,
    deleteFlg: 0,
    createdBy: 'admin',
    department: null,
    orgName: '',
    orgType: null,
    level: 1,
    birthDate: '',
    gender: null,
    residentId: '',
    residentIdDate: '',
    residentIdPlace: '',
    address: '',
    phone: '',
    startDate: s.createdDate.slice(0, 10),
    endDate: '',
    laborContract: '',
    laborContractStartDate: '',
    laborContractEndDate: '',
    approvalDocNo: '',
    approvalDocDate: '',
    caExpireDate: '',
    twoFactor: null,
    description: '',
    lastPasswordChangedDate: null,
    password: DEMO_PASSWORD,
    mustChangePassword: false,
    ...s,
  };
}

/** Thông tin cá nhân minh họa — không phải dữ liệu thật của ai. */
const PERSON = {
  residentIdPlace: 'Cục Cảnh sát QLHC về TTXH',
  address: 'Số 2 Phan Chu Trinh, phường Cửa Nam, TP. Hà Nội',
};

export const SEED_ACCOUNTS: readonly AccountRow[] = [
  /* ------------------------------------------------ nội bộ — persona */
  acc({
    loginName: 'admin',
    accountType: 'INTERNAL',
    fullName: 'Anh Tuấn - Quản trị Hệ thống',
    email: 'tuan.admin@hnx.vn',
    phone: '0901000001',
    department: 'CNTT',
    role: 'ROLE_SYS_ADMIN',
    birthDate: '1985-04-12',
    gender: 1,
    residentId: '001085012345',
    residentIdDate: '2021-06-10',
    ...PERSON,
    twoFactor: 'CA',
    caExpireDate: '2027-12-31',
    approvalDocNo: '01/QĐ-SGDHN',
    approvalDocDate: '2021-01-04',
    createdDate: '2021-01-05T08:00:00+07:00',
    lastPasswordChangedDate: '2026-06-30',
  }),
  acc({
    loginName: 'huong_qlny',
    accountType: 'INTERNAL',
    fullName: 'Chị Hương - Chuyên viên P.QLNY',
    email: 'huong.qlny@hnx.vn',
    phone: '0901234567',
    department: 'NY',
    role: 'ROLE_QLNY_STAFF',
    birthDate: '1992-09-03',
    gender: 0,
    residentId: '001192034567',
    residentIdDate: '2021-08-20',
    ...PERSON,
    laborContract: 'HĐLĐ-2022/118',
    laborContractStartDate: '2022-03-14',
    createdDate: '2022-03-14T09:10:00+07:00',
  }),
  acc({
    loginName: 'dung_tttt',
    accountType: 'INTERNAL',
    fullName: 'Anh Dũng - Lãnh đạo P.TTTT',
    email: 'dung.tttt@hnx.vn',
    phone: '0901234568',
    department: 'TT',
    role: 'ROLE_TTTT_MANAGER',
    birthDate: '1980-02-17',
    gender: 1,
    residentId: '001080045678',
    residentIdDate: '2021-05-02',
    ...PERSON,
    twoFactor: 'CA',
    caExpireDate: '2026-11-30',
    createdDate: '2022-06-20T14:00:00+07:00',
  }),
  acc({
    loginName: 'nam_cntt',
    accountType: 'INTERNAL',
    fullName: 'Anh Nam - Chuyên viên P.CNTT',
    email: 'nam.cntt@hnx.vn',
    phone: '0901234570',
    department: 'CNTT',
    role: 'ROLE_CNTT_STAFF',
    birthDate: '1995-11-22',
    gender: 1,
    residentId: '001095056789',
    residentIdDate: '2022-01-15',
    ...PERSON,
    createdDate: '2023-08-01T08:30:00+07:00',
  }),
  acc({
    loginName: 'thao_cntt',
    accountType: 'INTERNAL',
    fullName: 'Chị Thảo - Lãnh đạo P.CNTT',
    email: 'thao.cntt@hnx.vn',
    phone: '0901234571',
    department: 'CNTT',
    role: 'ROLE_CNTT_MANAGER',
    birthDate: '1983-07-08',
    gender: 0,
    residentId: '001183067890',
    residentIdDate: '2021-04-11',
    ...PERSON,
    createdDate: '2021-11-18T10:00:00+07:00',
  }),

  /* ------------------------------------------- nội bộ — Phòng Trái phiếu */
  acc({
    loginName: 'lan.nt',
    accountType: 'INTERNAL',
    fullName: 'Ngô Thị Lan',
    email: 'lan.nt@hnx.vn',
    phone: '0901234572',
    department: 'TP',
    level: 1,
    role: 'ROLE_TTTP_MANAGER',
    birthDate: '1984-01-30',
    gender: 0,
    residentId: '001184078901',
    residentIdDate: '2021-03-09',
    ...PERSON,
    twoFactor: 'GA',
    description: 'Admin cấp 1 Phòng Trái phiếu',
    createdDate: '2020-01-15T08:00:00+07:00',
  }),
  acc({
    loginName: 'minh.dv',
    accountType: 'INTERNAL',
    fullName: 'Đỗ Văn Minh',
    email: 'minh.dv@hnx.vn',
    phone: '0901234573',
    department: 'TP',
    level: 2,
    role: 'ROLE_TTTP_STAFF',
    birthDate: '1990-05-19',
    gender: 1,
    residentId: '001090089012',
    residentIdDate: '2021-09-27',
    ...PERSON,
    twoFactor: 'CA',
    caExpireDate: '2027-03-31',
    createdDate: '2021-11-18T15:20:00+07:00',
  }),
  acc({
    loginName: 'ha.pt',
    accountType: 'INTERNAL',
    fullName: 'Phạm Thu Hà',
    email: 'ha.pt@hnx.vn',
    phone: '0901234574',
    department: 'TP',
    level: 3,
    role: 'ROLE_TTTP_STAFF',
    birthDate: '1997-12-02',
    gender: 0,
    residentId: '001197090123',
    residentIdDate: '2022-02-14',
    ...PERSON,
    twoFactor: 'SMS',
    createdDate: '2023-08-01T09:00:00+07:00',
  }),
  acc({
    loginName: 'hoa.lt',
    accountType: 'INTERNAL',
    fullName: 'Lê Thị Hoa',
    email: 'hoa.lt@hnx.vn',
    phone: '0901234575',
    department: 'TP',
    level: 3,
    role: 'ROLE_TTTP_STAFF',
    birthDate: '1998-03-25',
    gender: 0,
    residentId: '001198001234',
    residentIdDate: '2022-10-05',
    ...PERSON,
    description: 'Tài khoản mới — chưa đăng nhập lần đầu',
    createdBy: 'lan.nt',
    createdDate: '2026-09-20T10:15:00+07:00',
    password: 'Tam@2026hnx',
    mustChangePassword: true,
  }),

  /* ------------------------------------------------ nội bộ — phòng khác */
  acc({
    loginName: 'an.nv',
    accountType: 'INTERNAL',
    fullName: 'Nguyễn Văn An',
    email: 'an.nv@hnx.vn',
    phone: '0901234576',
    department: 'NY',
    role: 'ROLE_QLNY_MANAGER',
    birthDate: '1981-10-10',
    gender: 1,
    residentId: '001081012346',
    residentIdDate: '2021-07-19',
    ...PERSON,
    twoFactor: 'GA',
    createdDate: '2022-03-14T08:00:00+07:00',
  }),
  acc({
    loginName: 'bich.tt',
    accountType: 'INTERNAL',
    fullName: 'Trần Thị Bích',
    email: 'bich.tt@hnx.vn',
    phone: '0901234577',
    department: 'NY',
    role: 'ROLE_QLNY_STAFF',
    birthDate: '1994-06-06',
    gender: 0,
    residentId: '001194023457',
    residentIdDate: '2021-12-01',
    ...PERSON,
    statusFlg: 0,
    endDate: '2026-06-30',
    description: 'Nghỉ việc từ 30/06/2026',
    createdDate: '2022-06-20T09:30:00+07:00',
  }),
  acc({
    loginName: 'cuong.lq',
    accountType: 'INTERNAL',
    fullName: 'Lê Quốc Cường',
    email: 'cuong.lq@hnx.vn',
    phone: '0901234578',
    department: 'TT',
    role: 'ROLE_TTTT_STAFF',
    birthDate: '1993-08-14',
    gender: 1,
    residentId: '001093034568',
    residentIdDate: '2022-04-22',
    ...PERSON,
    twoFactor: 'SMS',
    createdDate: '2023-02-10T13:45:00+07:00',
  }),

  /* ---------------------------------------------------------- tổ chức */
  acc({
    loginName: 'linh_vinamilk',
    accountType: 'EXTERNAL',
    fullName: 'Bạn Linh - Chuyên viên CBTT Vinamilk',
    email: 'linh.cbtt@vinamilk.com.vn',
    phone: '028 5415 5555',
    orgName: 'Công ty Cổ phần Sữa Việt Nam',
    orgType: 'Tổ chức phát hành',
    level: 1,
    role: 'ROLE_ORG_STAFF',
    twoFactor: 'SMS',
    createdDate: '2021-06-01T08:00:00+07:00',
  }),
  acc({
    loginName: 'hpg.cbtt',
    accountType: 'EXTERNAL',
    fullName: 'Bộ phận CBTT - Hòa Phát',
    email: 'cbtt@hoaphat.com.vn',
    phone: '024 6284 8666',
    orgName: 'Công ty Cổ phần Tập đoàn Hòa Phát',
    orgType: 'Tổ chức phát hành',
    level: 1,
    role: 'ROLE_ORG_MANAGER',
    createdDate: '2021-09-15T09:00:00+07:00',
  }),
  acc({
    loginName: 'bidv.cbtt',
    accountType: 'EXTERNAL',
    fullName: 'Bộ phận CBTT - BIDV',
    email: 'cbtt@bidv.com.vn',
    phone: '024 2220 5544',
    orgName: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam',
    orgType: 'Tổ chức phát hành',
    level: 1,
    role: 'ROLE_ORG_MANAGER',
    twoFactor: 'CA',
    caExpireDate: '2027-06-30',
    createdDate: '2021-10-04T10:30:00+07:00',
  }),
  acc({
    loginName: 'ssi.cbtt',
    accountType: 'EXTERNAL',
    fullName: 'Bộ phận CBTT - SSI',
    email: 'cbtt@ssi.com.vn',
    phone: '024 3936 6321',
    orgName: 'Công ty Cổ phần Chứng khoán SSI',
    orgType: 'Tổ chức phát hành',
    level: 2,
    role: 'ROLE_ORG_STAFF',
    createdDate: '2022-01-12T14:00:00+07:00',
  }),
  acc({
    loginName: 'ais.qlhat3',
    accountType: 'EXTERNAL',
    fullName: 'QLHAT3 - CTCP Chứng khoán AIS',
    email: 'qlhat3@ais.com.vn',
    phone: '024 3823 5566',
    orgName: 'Công ty Cổ phần Chứng khoán AIS',
    orgType: 'Tổ chức liên quan',
    level: 1,
    role: 'ROLE_ORG_MANAGER',
    twoFactor: 'GA',
    createdDate: '2022-05-09T08:45:00+07:00',
  }),
  acc({
    loginName: 'vps.giaodich',
    accountType: 'EXTERNAL',
    fullName: 'Bộ phận Giao dịch - VPS',
    email: 'giaodich@vps.com.vn',
    phone: '024 3934 3888',
    orgName: 'Công ty Cổ phần Chứng khoán VPS',
    orgType: 'Tổ chức liên quan',
    level: 1,
    role: 'ROLE_ORG_STAFF',
    createdDate: '2022-07-21T11:00:00+07:00',
  }),
  acc({
    loginName: 'tcbs.cbtt',
    accountType: 'EXTERNAL',
    fullName: 'Bộ phận CBTT - TCBS',
    email: 'cbtt@tcbs.com.vn',
    phone: '028 3823 4159',
    orgName: 'Công ty Cổ phần Chứng khoán Kỹ Thương (TCBS)',
    orgType: 'Tổ chức liên quan',
    level: 1,
    role: 'ROLE_ORG_STAFF',
    twoFactor: 'SMS',
    createdDate: '2023-01-05T09:20:00+07:00',
  }),
  acc({
    loginName: 'mbs.giaodich',
    accountType: 'EXTERNAL',
    fullName: 'Bộ phận Giao dịch - MBS',
    email: 'giaodich@mbs.com.vn',
    phone: '024 7304 5688',
    orgName: 'Công ty Cổ phần Chứng khoán MB (MBS)',
    orgType: 'Tổ chức liên quan',
    level: 2,
    role: 'ROLE_ORG_STAFF',
    statusFlg: 0,
    description: 'Tạm khóa theo đề nghị của MBS',
    createdDate: '2023-03-17T15:10:00+07:00',
  }),
  acc({
    loginName: 'vnd.luuky',
    accountType: 'EXTERNAL',
    fullName: 'Bộ phận Lưu ký - VNDIRECT',
    email: 'luuky@vndirect.com.vn',
    phone: '024 3972 4568',
    orgName: 'Công ty Cổ phần Chứng khoán VNDIRECT',
    orgType: 'Tổ chức liên quan',
    level: 1,
    role: 'ROLE_ORG_MANAGER',
    createdDate: '2023-06-02T08:00:00+07:00',
  }),
  acc({
    loginName: 'ndt.nguyenha',
    accountType: 'EXTERNAL',
    fullName: 'Nguyễn Thu Hà',
    email: 'nguyenha.ndt@gmail.com',
    phone: '0912345678',
    orgName: 'Công ty Cổ phần Chứng khoán SSI',
    orgType: 'Tổ chức phát hành',
    level: 3,
    role: 'ROLE_INVESTOR',
    createdBy: 'ssi.cbtt',
    createdDate: '2024-02-19T16:30:00+07:00',
  }),
];

/**
 * Lịch sử chỉnh sửa mẫu — Hình 1.4 của SRS dùng đúng ba dòng Phòng ban / Vai trò /
 * Trạng thái; ở đây gắn vào các tài khoản có thật trong danh sách.
 */
export const SEED_AUDIT: readonly AccountAuditEntry[] = [
  {
    id: 1,
    accountId: 10,
    at: '2026-03-15T09:12:00+07:00',
    by: 'admin',
    action: 'UPDATE',
    field: 'Phòng ban',
    oldValue: 'Phòng Thị trường',
    newValue: 'Phòng Niêm yết',
  },
  {
    id: 2,
    accountId: 10,
    at: '2026-02-02T14:40:00+07:00',
    by: 'admin',
    action: 'UPDATE',
    field: 'Vai trò',
    oldValue: 'Chuyên viên P.QLNY',
    newValue: 'Lãnh đạo P.QLNY',
  },
  {
    id: 3,
    accountId: 11,
    at: '2026-06-30T17:05:00+07:00',
    by: 'huong_qlny',
    action: 'UPDATE',
    field: 'Trạng thái',
    oldValue: 'Đang hoạt động',
    newValue: 'Ngừng hoạt động',
  },
  {
    id: 4,
    accountId: 9,
    at: '2026-09-20T10:15:00+07:00',
    by: 'lan.nt',
    action: 'CREATE',
    field: 'Tài khoản',
    oldValue: '',
    newValue: 'Tạo mới tài khoản',
  },
];
