/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { AttachedFile, Registration, RegistrationDraft } from './registrationTypes';

/**
 * Hồ sơ đăng ký chuyên trang mẫu — tên tổ chức, MST, người đại diện đều là dữ
 * liệu minh họa.
 *
 * Hai hồ sơ ĐÃ PHÊ DUYỆT trỏ đúng tên tổ chức đã có trong danh mục (POW ở TCPH,
 * Mirae Asset ở Tổ chức liên quan) và đều có file "Danh sách người sử dụng" — để
 * widget Trang chủ (IMS-018-8) hiện được nút "Thông tin tài khoản đã đăng ký"
 * ngay từ đầu, không phải tự phê duyệt một hồ sơ mới xem.
 */

const FORM: AttachedFile = {
  name: 'Don-dang-ky-chuyen-trang.pdf',
  description: 'Đơn đăng ký có chữ ký, đóng dấu của người đại diện pháp luật',
  type: 'PDF',
  sizeKb: 412,
};

const USERS: AttachedFile = {
  name: 'Danh-sach-nguoi-su-dung.xlsx',
  description: 'Danh sách người sử dụng theo mẫu HNX',
  type: 'XLSX',
  sizeKb: 38,
};

const BLANK: RegistrationDraft = {
  orgName: '',
  shortName: '',
  orgNameEn: '',
  taxCode: '',
  orgType: '',
  enterpriseType: '',
  jscType: '',
  publicCompanyType: '',
  businessSector: '',
  enterpriseCode: '',
  depositoryCode: '',
  tradingCode: '',
  domesticForeign: 'Trong nước',
  securitiesBusinessLine: '',
  operationStartDate: '',
  charterCapital: null,
  address: '',
  email: '',
  phone: '',
  fax: '',
  legalRep: '',
  legalRepPhone: '',
  legalRepEmail: '',
  authorizedPerson: '',
  authorizedPhone: '',
  authorizedEmail: '',
  initialLicenseNo: '',
  initialLicenseDate: '',
  initialLicensePlace: '',
  initialBizRegNo: '',
  initialBizRegDate: '',
  initialBizRegPlace: '',
  registrationFiles: [FORM],
  userListFiles: [USERS],
  adjustedLicenseNo: '',
  adjustedLicenseDate: '',
  adjustedLicensePlace: '',
  adjustedBizRegNo: '',
  adjustedBizRegDate: '',
  adjustedBizRegPlace: '',
};

let seedId = 0;
function reg(
  d: Partial<RegistrationDraft> & Pick<RegistrationDraft, 'orgName' | 'orgType' | 'taxCode'>,
  meta: Partial<Registration> & Pick<Registration, 'createdDate'>,
): Registration {
  seedId += 1;
  return {
    ...BLANK,
    ...d,
    id: seedId,
    status: 'PENDING',
    updatedDate: null,
    approvedBy: null,
    approvedDate: null,
    rejectedBy: null,
    rejectedDate: null,
    rejectReason: null,
    ...meta,
  };
}

const UBCK = 'Ủy ban Chứng khoán Nhà nước';
const SKHDT_HN = 'Sở Kế hoạch và Đầu tư TP. Hà Nội';

export const SEED_REGISTRATIONS: readonly Registration[] = [
  reg(
    {
      orgName: 'Công ty Cổ phần Chứng khoán An Phát',
      shortName: 'APS',
      orgNameEn: 'An Phat Securities Joint Stock Company',
      taxCode: '0109876543',
      orgType: 'Tổ chức phát hành',
      enterpriseType: 'Công ty cổ phần',
      jscType: 'Đã đại chúng',
      publicCompanyType: 'Công ty đăng ký giao dịch (UPCoM)',
      businessSector: 'Chứng khoán',
      securitiesBusinessLine: 'Môi giới chứng khoán; Tự doanh chứng khoán; Tư vấn đầu tư chứng khoán',
      enterpriseCode: 'DN-APS01',
      tradingCode: 'APS',
      operationStartDate: '2026-08-04',
      charterCapital: 300000000000,
      address: 'Tầng 8, số 25 Láng Hạ, phường Láng Hạ, TP. Hà Nội',
      email: 'info@anphatsec.vn',
      phone: '024 3772 8899',
      legalRep: 'Nguyễn Minh Khôi',
      legalRepPhone: '0913 222 111',
      legalRepEmail: 'khoi.nm@anphatsec.vn',
      authorizedPerson: 'Phạm Thị Thu',
      authorizedPhone: '0913 222 333',
      authorizedEmail: 'cbtt@anphatsec.vn',
      initialLicenseNo: '112/GP-UBCK',
      initialLicenseDate: '2026-07-01',
      initialLicensePlace: UBCK,
      initialBizRegNo: '0109876543',
      initialBizRegDate: '2026-06-15',
      initialBizRegPlace: SKHDT_HN,
      adjustedLicenseNo: '112/GP-UBCK',
      adjustedLicenseDate: '2026-07-01',
      adjustedLicensePlace: UBCK,
      adjustedBizRegNo: '0109876543',
      adjustedBizRegDate: '2026-06-15',
      adjustedBizRegPlace: SKHDT_HN,
    },
    { createdDate: '2026-09-10T09:15:00+07:00' },
  ),
  reg(
    {
      orgName: 'Ngân hàng TMCP Việt Thịnh',
      shortName: 'VTB',
      orgNameEn: 'Viet Thinh Commercial Joint Stock Bank',
      taxCode: '0301234567',
      orgType: 'Tổ chức phát hành',
      enterpriseType: 'Ngân hàng thương mại cổ phần',
      businessSector: 'Ngân hàng',
      enterpriseCode: 'DN-VTB01',
      operationStartDate: '2026-08-20',
      charterCapital: 5000000000000,
      address: '72 Nguyễn Huệ, phường Sài Gòn, TP. Hồ Chí Minh',
      email: 'contact@vietthinhbank.vn',
      phone: '028 3821 6868',
      legalRep: 'Trần Quang Vinh',
      legalRepPhone: '0908 111 222',
      legalRepEmail: 'vinh.tq@vietthinhbank.vn',
      initialLicenseNo: '45/GP-NHNN',
      initialLicenseDate: '2026-05-12',
      initialLicensePlace: 'Ngân hàng Nhà nước Việt Nam',
      initialBizRegNo: '0301234567',
      initialBizRegDate: '2026-05-20',
      initialBizRegPlace: 'Sở Kế hoạch và Đầu tư TP. Hồ Chí Minh',
      adjustedLicenseNo: '45/GP-NHNN',
      adjustedLicenseDate: '2026-05-12',
      adjustedLicensePlace: 'Ngân hàng Nhà nước Việt Nam',
      adjustedBizRegNo: '0301234567',
      adjustedBizRegDate: '2026-05-20',
      adjustedBizRegPlace: 'Sở Kế hoạch và Đầu tư TP. Hồ Chí Minh',
      // Chưa đính kèm danh sách người sử dụng — phải bổ sung mới phê duyệt được.
      userListFiles: [],
    },
    { createdDate: '2026-09-12T14:30:00+07:00' },
  ),
  reg(
    {
      orgName: 'Công ty TNHH Kiểm toán Tâm Việt',
      shortName: 'TVA',
      taxCode: '0108765432',
      orgType: 'Tổ chức liên quan',
      businessSector: 'Thương mại - Dịch vụ',
      enterpriseCode: 'DN-TVA01',
      operationStartDate: '2026-09-01',
      charterCapital: 20000000000,
      address: 'Số 15 Trần Hưng Đạo, phường Cửa Nam, TP. Hà Nội',
      email: 'audit@tamviet.vn',
      phone: '024 3942 1188',
      legalRep: 'Lê Hoàng Nam',
      legalRepPhone: '0987 654 321',
      legalRepEmail: 'nam.lh@tamviet.vn',
      initialLicenseNo: '09/GCN-BTC',
      initialLicenseDate: '2026-08-15',
      initialLicensePlace: 'Bộ Tài chính',
      initialBizRegNo: '0108765432',
      initialBizRegDate: '2026-08-01',
      initialBizRegPlace: SKHDT_HN,
      adjustedLicenseNo: '09/GCN-BTC',
      adjustedLicenseDate: '2026-08-15',
      adjustedLicensePlace: 'Bộ Tài chính',
      adjustedBizRegNo: '0108765432',
      adjustedBizRegDate: '2026-08-01',
      adjustedBizRegPlace: SKHDT_HN,
    },
    { createdDate: '2026-09-18T08:40:00+07:00' },
  ),
  reg(
    {
      orgName: 'Quỹ Đầu tư Phát triển Hà Nội',
      shortName: 'HDIF',
      taxCode: '0100112233',
      orgType: 'Tổ chức khác',
      businessSector: 'Khác',
      enterpriseCode: 'TC-HDIF',
      depositoryCode: 'HDIF',
      operationStartDate: '2026-09-15',
      charterCapital: 1000000000000,
      address: 'Số 5 Lý Thái Tổ, phường Hoàn Kiếm, TP. Hà Nội',
      email: 'info@hdif.gov.vn',
      phone: '024 3825 0011',
      legalRep: 'Hoàng Văn Đức',
      legalRepPhone: '0904 333 444',
      legalRepEmail: 'duc.hv@hdif.gov.vn',
      initialLicenseNo: '1234/QĐ-UBND',
      initialLicenseDate: '2026-07-20',
      initialLicensePlace: 'UBND TP. Hà Nội',
      initialBizRegNo: '0100112233',
      initialBizRegDate: '2026-07-25',
      initialBizRegPlace: SKHDT_HN,
      adjustedLicenseNo: '1234/QĐ-UBND',
      adjustedLicenseDate: '2026-07-20',
      adjustedLicensePlace: 'UBND TP. Hà Nội',
      adjustedBizRegNo: '0100112233',
      adjustedBizRegDate: '2026-07-25',
      adjustedBizRegPlace: SKHDT_HN,
    },
    { createdDate: '2026-09-22T10:05:00+07:00' },
  ),
  reg(
    {
      orgName: 'Công ty Cổ phần Đầu tư Hạ tầng Bắc Hà',
      shortName: 'BHI',
      taxCode: '0105556677',
      orgType: 'Tổ chức phát hành',
      enterpriseType: 'Công ty cổ phần',
      jscType: 'Chưa đại chúng',
      businessSector: 'Xây dựng',
      enterpriseCode: 'DN-BHI01',
      domesticForeign: 'Nước ngoài',
      operationStartDate: '2026-09-04',
      charterCapital: 800000000000,
      address: 'KCN Quang Minh, xã Quang Minh, TP. Hà Nội',
      email: 'ir@bachainfra.vn',
      phone: '024 3818 7766',
      legalRep: 'Kim Sung Ho',
      legalRepPhone: '0909 777 888',
      legalRepEmail: 'sungho.kim@bachainfra.vn',
      initialLicenseNo: '0105556677',
      initialLicenseDate: '2026-06-01',
      initialLicensePlace: SKHDT_HN,
      initialBizRegNo: '0105556677',
      initialBizRegDate: '2026-06-01',
      initialBizRegPlace: SKHDT_HN,
      // Chưa từng điều chỉnh — bước 5 để trống, phê duyệt sẽ báo thiếu.
    },
    { createdDate: '2026-09-24T16:20:00+07:00' },
  ),
  reg(
    {
      orgName: 'Tổng Công ty Điện lực Dầu khí Việt Nam',
      shortName: 'POW',
      taxCode: '0102276173',
      orgType: 'Tổ chức phát hành',
      enterpriseType: 'Công ty cổ phần',
      jscType: 'Đã đại chúng',
      publicCompanyType: 'Công ty niêm yết',
      businessSector: 'Năng lượng',
      enterpriseCode: 'DN-POW01',
      tradingCode: 'POW',
      operationStartDate: '2026-08-04',
      charterCapital: 23418716000000,
      address: 'Tầng 8-15, tòa nhà PetroVietnam, số 1-5 Lê Duẩn, TP. Hồ Chí Minh',
      email: 'cbtt@pvpower.vn',
      phone: '028 3910 3688',
      legalRep: 'Lê Như Linh',
      legalRepPhone: '0903 456 789',
      legalRepEmail: 'linh.ln@pvpower.vn',
      initialLicenseNo: '0102276173',
      initialLicenseDate: '2007-05-31',
      initialLicensePlace: SKHDT_HN,
      initialBizRegNo: '0102276173',
      initialBizRegDate: '2007-05-31',
      initialBizRegPlace: SKHDT_HN,
      adjustedLicenseNo: '0102276173',
      adjustedLicenseDate: '2024-10-10',
      adjustedLicensePlace: 'Sở Kế hoạch và Đầu tư TP. Hồ Chí Minh',
      adjustedBizRegNo: '0102276173',
      adjustedBizRegDate: '2024-10-10',
      adjustedBizRegPlace: 'Sở Kế hoạch và Đầu tư TP. Hồ Chí Minh',
    },
    {
      createdDate: '2026-08-27T12:06:00+07:00',
      status: 'APPROVED',
      updatedDate: '2026-08-27T12:07:00+07:00',
      approvedBy: 'lan.nt',
      approvedDate: '2026-08-27T12:07:00+07:00',
    },
  ),
  reg(
    {
      orgName: 'Công ty TNHH Chứng khoán Mirae Asset (Việt Nam)',
      shortName: 'Mirae Asset',
      taxCode: '0305955155',
      orgType: 'Tổ chức liên quan',
      businessSector: 'Chứng khoán',
      securitiesBusinessLine: 'Môi giới; Tự doanh; Bảo lãnh phát hành chứng khoán',
      enterpriseCode: 'DN-MAS01',
      depositoryCode: '082',
      tradingCode: '082',
      domesticForeign: 'Nước ngoài',
      operationStartDate: '2026-07-15',
      charterCapital: 7800000000000,
      address: 'Tầng 7, tòa nhà Le Meridien, 3C Tôn Đức Thắng, TP. Hồ Chí Minh',
      email: 'dangky@miraeasset.com.vn',
      phone: '028 3910 2222',
      legalRep: 'Kang Moon Kyung',
      legalRepPhone: '0908 222 999',
      legalRepEmail: 'mk.kang@miraeasset.com.vn',
      initialLicenseNo: '117/GP-UBCK',
      initialLicenseDate: '2007-12-26',
      initialLicensePlace: UBCK,
      initialBizRegNo: '0305955155',
      initialBizRegDate: '2007-12-26',
      initialBizRegPlace: 'Sở Kế hoạch và Đầu tư TP. Hồ Chí Minh',
      adjustedLicenseNo: '35/GPĐC-UBCK',
      adjustedLicenseDate: '2025-04-02',
      adjustedLicensePlace: UBCK,
      adjustedBizRegNo: '0305955155',
      adjustedBizRegDate: '2025-04-02',
      adjustedBizRegPlace: 'Sở Kế hoạch và Đầu tư TP. Hồ Chí Minh',
    },
    {
      createdDate: '2026-07-20T09:00:00+07:00',
      status: 'APPROVED',
      updatedDate: '2026-07-21T10:30:00+07:00',
      approvedBy: 'an.nv',
      approvedDate: '2026-07-21T10:30:00+07:00',
    },
  ),
  reg(
    {
      orgName: 'Công ty TNHH Thương mại Minh Quang',
      shortName: 'Minh Quang',
      taxCode: '0107778899',
      orgType: 'Tổ chức khác',
      businessSector: 'Thương mại - Dịch vụ',
      enterpriseCode: 'TC-MQ01',
      operationStartDate: '2026-06-01',
      charterCapital: 5000000000,
      address: 'Số 88 Kim Mã, phường Giảng Võ, TP. Hà Nội',
      email: 'minhquang.tm@gmail.com',
      phone: '0978 123 456',
      legalRep: 'Đinh Văn Quang',
      legalRepPhone: '0978 123 457',
      legalRepEmail: 'quang.dv@gmail.com',
      initialLicenseNo: '0107778899',
      initialLicenseDate: '2026-05-10',
      initialLicensePlace: SKHDT_HN,
      initialBizRegNo: '0107778899',
      initialBizRegDate: '2026-05-10',
      initialBizRegPlace: SKHDT_HN,
      registrationFiles: [{ ...FORM, description: 'Đơn đăng ký (bản chụp, chưa đóng dấu)' }],
    },
    {
      createdDate: '2026-08-05T15:00:00+07:00',
      status: 'REJECTED',
      updatedDate: '2026-08-06T09:20:00+07:00',
      rejectedBy: 'minh.dv',
      rejectedDate: '2026-08-06T09:20:00+07:00',
      rejectReason: 'Đơn đăng ký chưa có chữ ký, đóng dấu của người đại diện theo pháp luật.',
    },
  ),
];
